data_schema:
  # 这里记录数据的scheme和数据类型
  - Y: int, target
  - YEARWEEK: datetime, main_time
  - SKU_ID: int

infra:
  current_env: dev
  dev:
    clickhouse:
      - name: clickhouse1
        host: xxx
        port: xx
        user: xx
        password: xx
  prod:
    clickhouse:
      - name: clickhouse1
        host: xxx
        port: xx
        user: xx
        password: xx
