# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/entity.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 3, "", "protos/entity.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13protos/entity.proto\x12\x06\x65ntity")\n\x06\x45ntity\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tjoin_keys\x18\x02 \x03(\t"5\n\x13\x43reateEntityRequest\x12\x1e\n\x06\x65ntity\x18\x01 \x01(\x0b\x32\x0e.entity.Entity"X\n\x14\x43reateEntityResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1e\n\x06\x65ntity\x18\x03 \x01(\x0b\x32\x0e.entity.Entity" \n\x10GetEntityRequest\x12\x0c\n\x04name\x18\x01 \x01(\t"S\n\x11GetEntityResponse\x12\x1e\n\x06\x65ntity\x18\x01 \x01(\x0b\x32\x0e.entity.Entity\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t2\x9c\x01\n\rEntityService\x12I\n\x0c\x43reateEntity\x12\x1b.entity.CreateEntityRequest\x1a\x1c.entity.CreateEntityResponse\x12@\n\tGetEntity\x12\x18.entity.GetEntityRequest\x1a\x19.entity.GetEntityResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "protos.entity_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ENTITY"]._serialized_start = 31
    _globals["_ENTITY"]._serialized_end = 72
    _globals["_CREATEENTITYREQUEST"]._serialized_start = 74
    _globals["_CREATEENTITYREQUEST"]._serialized_end = 127
    _globals["_CREATEENTITYRESPONSE"]._serialized_start = 129
    _globals["_CREATEENTITYRESPONSE"]._serialized_end = 217
    _globals["_GETENTITYREQUEST"]._serialized_start = 219
    _globals["_GETENTITYREQUEST"]._serialized_end = 251
    _globals["_GETENTITYRESPONSE"]._serialized_start = 253
    _globals["_GETENTITYRESPONSE"]._serialized_end = 336
    _globals["_ENTITYSERVICE"]._serialized_start = 339
    _globals["_ENTITYSERVICE"]._serialized_end = 495
# @@protoc_insertion_point(module_scope)
