# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: entity.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, "", "entity.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0c\x65ntity.proto\x12\x06\x65ntity"5\n\x06\x45ntity\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tjoin_keys\x18\x03 \x03(\t"6\n\x13\x43reateEntityRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tjoin_keys\x18\x02 \x03(\t"C\n\x14\x43reateEntityResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tjoin_keys\x18\x03 \x03(\t"9\n\x10GetEntityRequest\x12\x0c\n\x02id\x18\x01 \x01(\x05H\x00\x12\x0e\n\x04name\x18\x02 \x01(\tH\x00\x42\x07\n\x05query"3\n\x11GetEntityResponse\x12\x1e\n\x06\x65ntity\x18\x01 \x01(\x0b\x32\x0e.entity.Entity2\xa0\x01\n\rEntityService\x12K\n\x0c\x43reateEntity\x12\x1b.entity.CreateEntityRequest\x1a\x1c.entity.CreateEntityResponse"\x00\x12\x42\n\tGetEntity\x12\x18.entity.GetEntityRequest\x1a\x19.entity.GetEntityResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "entity_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ENTITY"]._serialized_start = 24
    _globals["_ENTITY"]._serialized_end = 77
    _globals["_CREATEENTITYREQUEST"]._serialized_start = 79
    _globals["_CREATEENTITYREQUEST"]._serialized_end = 133
    _globals["_CREATEENTITYRESPONSE"]._serialized_start = 135
    _globals["_CREATEENTITYRESPONSE"]._serialized_end = 202
    _globals["_GETENTITYREQUEST"]._serialized_start = 204
    _globals["_GETENTITYREQUEST"]._serialized_end = 261
    _globals["_GETENTITYRESPONSE"]._serialized_start = 263
    _globals["_GETENTITYRESPONSE"]._serialized_end = 314
    _globals["_ENTITYSERVICE"]._serialized_start = 317
    _globals["_ENTITYSERVICE"]._serialized_end = 477
# @@protoc_insertion_point(module_scope)
