"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Entity(google.protobuf.message.Message):
    """Entity 消息定义"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    JOIN_KEYS_FIELD_NUMBER: builtins.int
    name: builtins.str
    """对应 String(256), 主键"""
    @property
    def join_keys(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """对应 JSON List"""

    def __init__(
        self,
        *,
        name: builtins.str = ...,
        join_keys: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["join_keys", b"join_keys", "name", b"name"]) -> None: ...

global___Entity = Entity

@typing.final
class CreateEntityRequest(google.protobuf.message.Message):
    """创建 Entity 的请求消息"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTITY_FIELD_NUMBER: builtins.int
    @property
    def entity(self) -> global___Entity: ...
    def __init__(
        self,
        *,
        entity: global___Entity | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["entity", b"entity"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["entity", b"entity"]) -> None: ...

global___CreateEntityRequest = CreateEntityRequest

@typing.final
class CreateEntityResponse(google.protobuf.message.Message):
    """创建 Entity 的响应消息"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    ENTITY_FIELD_NUMBER: builtins.int
    success: builtins.bool
    message: builtins.str
    @property
    def entity(self) -> global___Entity: ...
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        message: builtins.str = ...,
        entity: global___Entity | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["entity", b"entity"]) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["entity", b"entity", "message", b"message", "success", b"success"]
    ) -> None: ...

global___CreateEntityResponse = CreateEntityResponse

@typing.final
class GetEntityRequest(google.protobuf.message.Message):
    """查询 Entity 的请求消息"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___GetEntityRequest = GetEntityRequest

@typing.final
class GetEntityResponse(google.protobuf.message.Message):
    """查询 Entity 的响应消息"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTITY_FIELD_NUMBER: builtins.int
    FOUND_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    found: builtins.bool
    message: builtins.str
    @property
    def entity(self) -> global___Entity: ...
    def __init__(
        self,
        *,
        entity: global___Entity | None = ...,
        found: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["entity", b"entity"]) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["entity", b"entity", "found", b"found", "message", b"message"]
    ) -> None: ...

global___GetEntityResponse = GetEntityResponse
