# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/feature.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 3, "", "protos/feature.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14protos/feature.proto\x12\x07\x66\x65\x61ture\x1a\x13protos/source.proto\x1a\x13protos/entity.proto"\xc9\x03\n\x07\x46\x65\x61ture\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x1e\n\x06source\x18\x03 \x01(\x0b\x32\x0e.source.Source\x12\x1e\n\x06\x65ntity\x18\x04 \x01(\x0b\x32\x0e.entity.Entity\x12\x1d\n\x15\x65vent_timestamp_field\x18\x05 \x01(\t\x12\x1c\n\x14start_event_datetime\x18\x06 \x01(\t\x12\x1a\n\x12\x65nd_event_datetime\x18\x07 \x01(\t\x12\x0b\n\x03ttl\x18\x08 \x01(\x03\x12,\n\x06schema\x18\t \x03(\x0b\x32\x1c.feature.Feature.SchemaEntry\x12(\n\x04sink\x18\n \x03(\x0b\x32\x1a.feature.Feature.SinkEntry\x12\x11\n\ttransform\x18\x0b \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x0c \x01(\t\x12\r\n\x05owner\x18\r \x01(\t\x12\x0e\n\x06status\x18\x0e \x01(\t\x1a-\n\x0bSchemaEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a+\n\tSinkEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "protos.feature_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_FEATURE_SCHEMAENTRY"]._loaded_options = None
    _globals["_FEATURE_SCHEMAENTRY"]._serialized_options = b"8\001"
    _globals["_FEATURE_SINKENTRY"]._loaded_options = None
    _globals["_FEATURE_SINKENTRY"]._serialized_options = b"8\001"
    _globals["_FEATURE"]._serialized_start = 76
    _globals["_FEATURE"]._serialized_end = 533
    _globals["_FEATURE_SCHEMAENTRY"]._serialized_start = 443
    _globals["_FEATURE_SCHEMAENTRY"]._serialized_end = 488
    _globals["_FEATURE_SINKENTRY"]._serialized_start = 490
    _globals["_FEATURE_SINKENTRY"]._serialized_end = 533
# @@protoc_insertion_point(module_scope)
