"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import protos.entity_pb2
import protos.source_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Feature(google.protobuf.message.Message):
    """Feature 消息定义"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class SchemaEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    @typing.final
    class SinkEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    NAME_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    ENTITY_FIELD_NUMBER: builtins.int
    EVENT_TIMESTAMP_FIELD_FIELD_NUMBER: builtins.int
    START_EVENT_DATETIME_FIELD_NUMBER: builtins.int
    END_EVENT_DATETIME_FIELD_NUMBER: builtins.int
    TTL_FIELD_NUMBER: builtins.int
    SCHEMA_FIELD_NUMBER: builtins.int
    SINK_FIELD_NUMBER: builtins.int
    TRANSFORM_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    OWNER_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    name: builtins.str
    """主键，特征名称"""
    version: builtins.str
    """主键，特征版本"""
    event_timestamp_field: builtins.str
    """事件时间戳字段"""
    start_event_datetime: builtins.str
    """开始事件时间（ISO 格式字符串表示 DateTime）"""
    end_event_datetime: builtins.str
    """结束事件时间（ISO 格式字符串表示 DateTime）"""
    ttl: builtins.int
    """生存时间（单位：秒，表示 Interval）"""
    transform: builtins.str
    """转换逻辑"""
    description: builtins.str
    """特征描述"""
    owner: builtins.str
    """拥有者"""
    status: builtins.str
    """状态，默认值为 "pending" """
    @property
    def source(self) -> protos.source_pb2.Source:
        """数据源信息，引用 source.proto 中的 Source"""

    @property
    def entity(self) -> protos.entity_pb2.Entity:
        """实体信息，引用 entity.proto 中的 Entity"""

    @property
    def schema(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """特征模式，使用 map 表示 JSON"""

    @property
    def sink(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """输出目标，使用 map 表示 JSON"""

    def __init__(
        self,
        *,
        name: builtins.str = ...,
        version: builtins.str = ...,
        source: protos.source_pb2.Source | None = ...,
        entity: protos.entity_pb2.Entity | None = ...,
        event_timestamp_field: builtins.str = ...,
        start_event_datetime: builtins.str = ...,
        end_event_datetime: builtins.str = ...,
        ttl: builtins.int = ...,
        schema: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        sink: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        transform: builtins.str = ...,
        description: builtins.str = ...,
        owner: builtins.str = ...,
        status: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["entity", b"entity", "source", b"source"]) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "description",
            b"description",
            "end_event_datetime",
            b"end_event_datetime",
            "entity",
            b"entity",
            "event_timestamp_field",
            b"event_timestamp_field",
            "name",
            b"name",
            "owner",
            b"owner",
            "schema",
            b"schema",
            "sink",
            b"sink",
            "source",
            b"source",
            "start_event_datetime",
            b"start_event_datetime",
            "status",
            b"status",
            "transform",
            b"transform",
            "ttl",
            b"ttl",
            "version",
            b"version",
        ],
    ) -> None: ...

global___Feature = Feature
