# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/source.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 3, "", "protos/source.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13protos/source.proto\x12\x06source"\xbc\x02\n\x06Source\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x12\n\ntable_name\x18\x03 \x01(\t\x12\x12\n\ninfra_type\x18\x04 \x01(\t\x12\x37\n\rfield_mapping\x18\x05 \x03(\x0b\x32 .source.Source.FieldMappingEntry\x12\r\n\x05owner\x18\x06 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x07 \x01(\t\x12*\n\x06\x63onfig\x18\x08 \x03(\x0b\x32\x1a.source.Source.ConfigEntry\x1a\x33\n\x11\x46ieldMappingEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "protos.source_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_SOURCE_FIELDMAPPINGENTRY"]._loaded_options = None
    _globals["_SOURCE_FIELDMAPPINGENTRY"]._serialized_options = b"8\001"
    _globals["_SOURCE_CONFIGENTRY"]._loaded_options = None
    _globals["_SOURCE_CONFIGENTRY"]._serialized_options = b"8\001"
    _globals["_SOURCE"]._serialized_start = 32
    _globals["_SOURCE"]._serialized_end = 348
    _globals["_SOURCE_FIELDMAPPINGENTRY"]._serialized_start = 250
    _globals["_SOURCE_FIELDMAPPINGENTRY"]._serialized_end = 301
    _globals["_SOURCE_CONFIGENTRY"]._serialized_start = 303
    _globals["_SOURCE_CONFIGENTRY"]._serialized_end = 348
# @@protoc_insertion_point(module_scope)
